- name: Ensure Vagrant Vm running
  hosts: localhost
  
  tasks:
  - name: Custom module start
    vm_vagrant:
      path: /home/student/cm/ansible/day-3
#state: started, stopped, destroyed
      state: started
    register: out

  - add_host:
      name: "{{out.IP}}"
      groups: just_created
      ansible_port: "{{out.port}}"
      ansible_connection: ssh
      ansible_user: "{{out.username}}"
      ansible_ssh_private_key_file: "{{out.ssh_key_file}}"
    when: out.status == "running"

- name: Installation
  hosts: just_created
  become: true
  
  roles:
  - nginx


- name: Verification
  hosts: just_created

  roles:
  - nginx_test
