- name: Ensure nginx is installed     
  yum:
    name: nginx
    state: present
  notify: nginx_service

- name: Ensure nginx config is updated
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - nginx_restart
    
- name: force all notified handlers to run at this point, not waiting for normal sync points 
  meta: flush_handlers

- name: Nginx config
  shell: cat /etc/nginx/nginx.conf
  register: output2
  notify: 
    - nginx_service

- name: Show Nginx config
  debug: var=output2