- name: Ensure Vagrant Vm running
  hosts: localhost
  
  tasks:
  - name: Custom module start
    vm_vagrant:
      path: /home/student/cm/ansible/day-3
#state: started, stopped, destroyed
      state: started
    register: out

